### ISSUE TITLE
CSS fixes

### ISSUE THREAD

**Issue by Californ1a** [Californ1a/chargeup#32]
Some mobile fixes:
```css
@media screen and (max-width: 575px) {
    .controls {
        grid-template-columns: 1fr;
        grid-template-rows: 1fr 1fr 1fr;
        grid-template-areas:
            "main-control-group"
            "right-control-group"
            "left-control-group";
        gap: 10px;
    }

    .left-control-group,
    .main-control-group,
    .right-control-group {
        margin: 0
    }

    .main-control-group] {
        max-width: unset;
    }
}

@media screen and (max-width: 375px) {
    .game {
        padding: 1rem 0.3rem;
    }
}
```

Controls grid names aren't properly applied, needs to be added:
```css
.left-control-group {
    grid-area: left-control-group
}

.main-control-group {
    grid-area: main-control-group
}

.right-control-group {
    grid-area: right-control-group
}
```
